export type { configInterface } from './dateConfig'
export type { dateFormatInterface } from './dateFormat'
export type { debounceInterface } from './debounce'
export type { deepCloneInterface } from './deepClone'
export type { getStorageInterface } from './getStorage'
export type { getTypeInterface } from './getType'
export type { isArrHaveInterface } from './isArrHave'
export type { isNumberInterface } from './isNumber'
export type { isTfInterface } from './isTf'
export type { isUndefinedInterface } from './isUndefined'
export type { keepDecimalInterface } from './keepDecimal'
export type { mergeArrayRepeatInterface } from './mergeArrayRepeat'
export type { nowTimeInterface } from './nowTime'
export type { onTypeErrorInterface } from './onError'
export type { onLineInterface } from './onLine'
export type {
  pastTimeInterface,
  configInterface as pastTimeConfigInterface
} from './pastTime'
export type { randomColorInterface } from './randomColor'
export type { randomNumInterface } from './randomNum'
export type { randomStringInterface } from './randomString'
export type { removeStorageInterface } from './removeStorage'
export type { setStorageInterface } from './setStorage'
export type { shallowCloneInterface } from './shallowClone'
export type { throttleInterface } from './throttle'
export type { uniqueArrayInterface } from './uniqueArray'
export type { witTenNumInterface } from './witTenNum'
